{
 "title": "NTHU Power Station",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "總計",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "power_station_1+power_station_2+power_station_3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "用電紀錄",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "power_station_1", "legendFormat": "北區一號" },
    { "expr": "power_station_2", "legendFormat": "北區二號" },
    { "expr": "power_station_3", "legendFormat": "仙宮" },
    {
     "expr": "power_station_1+power_station_2+power_station_3",
     "legendFormat": "總計"
    }
   ]
  },
  {
   "title": "北區一號",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "power_station_1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "北區二號",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "power_station_2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "仙宮",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "power_station_3", "legendFormat": "__auto" }
   ]
  }
 ]
}